#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hpg_cell_mqtt_correction_certs
 
include $(XPLR_HPG_SW_PATH)/project.mk

include $(IDF_PATH)/make/project.mk